export function renderAdminPage() {
  return `<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>RSI Weekly · 数据看板</title>
  <style>
    :root{--bg:#0b0e12;--panel:#14191f;--line:#29323c;--ink:#f4f6f8;--muted:#98a4af;--accent:#c7ff5e}
    *{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,"Noto Sans SC",system-ui,sans-serif}.shell{width:min(1180px,calc(100% - 32px));margin:auto;padding:32px 0 80px}header{display:flex;justify-content:space-between;align-items:end;margin-bottom:32px}h1{margin:8px 0 0;font-size:40px;letter-spacing:-.04em}.eyebrow{color:var(--accent);font:12px ui-monospace,monospace;letter-spacing:.14em}.stamp{color:var(--muted);font-size:12px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.card,.table-card{background:var(--panel);border:1px solid var(--line);border-radius:16px;padding:20px}.metric{font-size:32px;font-weight:800;margin-top:8px}.label{color:var(--muted);font-size:13px}.table-card{margin-top:16px;overflow:auto}h2{font-size:18px;margin:0 0 16px}table{width:100%;border-collapse:collapse;min-width:760px}th,td{text-align:left;padding:12px;border-bottom:1px solid var(--line);font-size:13px}th{color:var(--muted);font-weight:600}.error{color:#ff806e}@media(max-width:760px){.grid{grid-template-columns:1fr 1fr}header{align-items:start;flex-direction:column;gap:12px}}
  </style>
</head>
<body><main class="shell"><header><div><div class="eyebrow">PRIVATE PRODUCT ANALYTICS</div><h1>用户反馈回流</h1></div><div id="stamp" class="stamp">加载中…</div></header><section id="metrics" class="grid"></section><section class="table-card"><h2>论文表现</h2><table><thead><tr><th>arXiv</th><th>曝光</th><th>展开</th><th>展开率</th><th>全文打开</th><th>全文转化率</th><th>👍</th><th>👎</th></tr></thead><tbody id="papers"></tbody></table></section><section class="table-card"><h2>用户行为（匿名 ID）</h2><table><thead><tr><th>用户 ID</th><th>首次访问</th><th>最近访问</th><th>生成雷达</th><th>展开</th><th>全文打开</th><th>arXiv 点击</th><th>反馈</th></tr></thead><tbody id="users"></tbody></table></section><section class="table-card"><h2>推荐位表现</h2><table><thead><tr><th>位置</th><th>曝光</th><th>展开</th><th>展开率</th></tr></thead><tbody id="positions"></tbody></table></section><p id="error" class="error"></p></main>
<script>
const pct=v=>(v*100).toFixed(1)+'%';
async function load(){try{const r=await fetch('/api/admin/metrics');const d=await r.json();if(!r.ok)throw new Error(d.error||'加载失败');document.querySelector('#stamp').textContent='更新于 '+new Date(d.generatedAt).toLocaleString();const cards=[['独立用户',d.uniqueVisitors],['推荐列表浏览',d.funnel.digestViews],['论文展开率',pct(d.funnel.expansionRate)],['全文打开率',pct(d.funnel.fullReportRate)]];document.querySelector('#metrics').innerHTML=cards.map(([l,v])=>'<div class="card"><div class="label">'+l+'</div><div class="metric">'+v+'</div></div>').join('');document.querySelector('#papers').innerHTML=d.papers.map(p=>'<tr><td>'+p.arxivId+'</td><td>'+p.impressions+'</td><td>'+p.expansions+'</td><td>'+pct(p.expansionRate)+'</td><td>'+p.fullReports+'</td><td>'+pct(p.fullReportRate)+'</td><td>'+p.up+'</td><td>'+p.down+'</td></tr>').join('')||'<tr><td colspan="8">暂无数据</td></tr>';document.querySelector('#users').innerHTML=d.users.map(u=>'<tr><td title="'+u.userId+'">'+u.userId.slice(0,8)+'…</td><td>'+new Date(u.firstSeenAt).toLocaleString()+'</td><td>'+new Date(u.lastSeenAt).toLocaleString()+'</td><td>'+u.digestRequests+'</td><td>'+u.expansions+'</td><td>'+u.fullReportOpens+'</td><td>'+u.sourceClicks+'</td><td>'+u.votes+'</td></tr>').join('')||'<tr><td colspan="8">暂无数据</td></tr>';document.querySelector('#positions').innerHTML=d.positions.map(p=>'<tr><td>#'+(p.position+1)+'</td><td>'+p.impressions+'</td><td>'+p.expansions+'</td><td>'+pct(p.expansionRate)+'</td></tr>').join('')||'<tr><td colspan="4">暂无数据</td></tr>';}catch(e){document.querySelector('#error').textContent=e.message}}
load();
</script></body></html>`;
}
