export function chatStyles() {
  return `<style>
    #chatOpen{width:100%;margin-top:12px}.chat-section[hidden],.chat-section [hidden]{display:none!important}
    .chat-section{margin-top:44px}.chat-heading{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:18px}.chat-heading>button{flex-shrink:0}.chat-heading h2{font-size:28px;letter-spacing:-.03em;margin:6px 0}.chat-heading p{margin:8px 0;color:var(--muted);font-size:14px;line-height:1.6}
    .chat-layout{display:grid;grid-template-columns:210px minmax(0,1fr);border:1px solid var(--line);border-radius:22px;overflow:hidden;background:#10151bed}.chat-sidebar{padding:18px;border-right:1px solid var(--line);background:#0d1116}.chat-sidebar>button{width:100%}.chat-history{display:flex;flex-direction:column;gap:8px;margin-top:18px}.chat-history button{text-align:left;background:transparent;color:var(--muted);font-weight:500;line-height:1.5;overflow-wrap:anywhere;border:1px solid transparent}.chat-history button.selected{border-color:#5ef3d155;background:#16322b;color:var(--ink)}
    .chat-main{min-width:0}.chat-messages{height:400px;overflow:auto;padding:24px;display:flex;flex-direction:column;gap:18px}.chat-welcome{margin:auto;max-width:450px}.chat-welcome h3{font-size:24px;line-height:1.5}.chat-welcome p{color:var(--muted);line-height:1.8;font-size:14px}.chat-suggestions{display:flex;flex-wrap:wrap;gap:8px}.chat-suggestions button{text-align:left;font-size:12px;line-height:1.6}
    .chat-message{max-width:95%;overflow-wrap:anywhere}.chat-message.user{align-self:flex-end;max-width:85%}.chat-role{color:var(--accent2);font-size:11px;letter-spacing:.04em;margin-bottom:6px}.chat-message.user .chat-role{text-align:right;color:var(--muted)}.chat-bubble{padding:14px 18px;border-radius:16px;background:#1b232d;line-height:1.8;font-size:14px}.user .chat-bubble{background:#23402f;white-space:pre-wrap}.chat-bubble p{margin:0 0 10px}.chat-bubble p:last-child{margin-bottom:0}.chat-bubble a{color:var(--accent2)}.chat-bubble ul,.chat-bubble ol{padding-left:20px}.chat-bubble pre{overflow:auto}.chat-bubble table{display:block;overflow:auto}
    .chat-composer{padding:18px 24px;border-top:1px solid var(--line)}.chat-status{font-size:12px;color:var(--accent2);min-height:20px;margin:0 0 8px}.chat-composer textarea{resize:vertical;min-height:85px;width:100%;padding:14px;background:#0b1015;color:var(--ink);border:1px solid var(--line);border-radius:12px;font:14px/1.6 inherit;outline:none}.chat-composer textarea:focus{border-color:var(--accent2)}.chat-controls{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-top:10px}.chat-controls span{font-size:11px;color:var(--muted)}.chat-recommend{border-top:1px solid var(--line);padding:18px 24px;background:#132018}.chat-recommend button{width:100%}.chat-recommend p{font-size:12px;color:var(--muted);line-height:1.7;margin:10px 0 0}.chat-results{display:flex;gap:10px;flex-wrap:wrap;margin-top:12px}.chat-results a{font-size:12px;color:var(--accent2)}.chat-error{color:var(--danger);font-size:13px;line-height:1.6;margin:10px 0 0;min-height:18px}
    @media(max-width:760px){.chat-layout{grid-template-columns:1fr}.chat-sidebar{border-right:0;border-bottom:1px solid var(--line)}.chat-history{flex-direction:row;overflow:auto;max-height:100px}.chat-history button{min-width:150px}.chat-messages{height:380px;padding:18px}.chat-heading{align-items:start}.chat-controls span{max-width:180px}.chat-composer,.chat-recommend{padding:16px}}
  </style>`;
}

export function chatSection() {
  return `<section id="chatSection" class="chat-section" hidden>
    <div class="chat-heading"><div><div class="eyebrow">YOUR RESEARCH, YOUR WAY</div><h2>先聊偏好，再找值得读的论文</h2><p>告诉我你关注什么，我们可以一起收窄方向，也可以随时调整。</p></div><button id="chatHide" class="ghost" type="button">收起对话</button></div>
    <div class="chat-layout"><aside class="chat-sidebar"><button id="chatNew" class="secondary" type="button">＋ 新建对话</button><div id="chatHistory" class="chat-history" aria-label="我的研究对话"></div></aside>
    <div class="chat-main"><div id="chatMessages" class="chat-messages" role="log" aria-label="研究偏好对话" aria-live="polite"></div>
    <form id="chatForm" class="chat-composer"><p id="chatStatus" class="chat-status" role="status"></p><label for="chatInput" class="basis">你的关注方向或问题</label><textarea id="chatInput" maxlength="4000" placeholder="比如：我关注能落地的自我改进 Agent，想看有代码、有实验对比的论文…" required></textarea><div class="chat-controls"><span>Enter 发送 · Shift + Enter 换行</span><button id="chatSend" type="submit">发送</button></div><p id="chatError" class="chat-error" role="alert"></p></form>
    <div class="chat-recommend"><button id="chatRecommend" type="button" disabled>按当前偏好生成推荐</button><p>结合整段对话筛选近七天论文，并自动准备每篇全文解读。对话仅当前浏览器身份可见。</p><div id="chatResults" class="chat-results"></div></div></div></div>
  </section>`;
}

export function chatScript(basePath, initialTarget) {
  return `<script>
  (()=>{
    const prefix=${JSON.stringify(basePath)},initial=${JSON.stringify(initialTarget)};
    const $=s=>document.querySelector(s), section=$('#chatSection'), input=$('#chatInput');
    let current=null,chatList=[],timer=null,busy=false,sendAttempt=null,recommendAttempt=null,renderedMessages='';
    const newId=()=>Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('');
    const node=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e};
    async function api(path,options){const r=await fetch(prefix+path,options);let d;try{d=await r.json()}catch{throw new Error('服务暂时不可用，请稍后重试。')}if(!r.ok)throw new Error(d.error||'请求失败');return d}
    const post=(path,body)=>api(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
    function controls(){const pending=current?.status==='running';$('#chatSend').disabled=busy||pending||current?.status==='terminated';$('#chatNew').disabled=busy;$('#chatRecommend').disabled=busy||pending||!current?.messages.some(m=>m.role==='assistant');$('#chatStatus').textContent=pending?'正在回复…消息会自动更新，你也可以稍后回来继续。':current?'可以继续补充偏好，或生成推荐。':'先说说你希望找到什么样的论文。'}
    function history(){const box=$('#chatHistory');box.replaceChildren();for(const chat of chatList){const b=node('button',chat.id===current?.id?'selected':'',chat.title);b.type='button';b.onclick=()=>{if(!busy)openChat(chat.id)};box.append(b)}}
    async function refreshHistory(){chatList=(await api('/api/chats')).chats;history()}
    function welcome(){const box=$('#chatMessages');box.replaceChildren();const wrap=node('div','chat-welcome');wrap.append(node('h3','','你更想解决什么问题？'),node('p','','可以从研究方向、工程目标或阅读习惯聊起。我们会逐步明确偏好，再生成适合你的推荐。'));const suggestions=node('div','chat-suggestions');for(const text of ['我关注有开源代码的自我改进 Agent','我想了解 RSI 的理论与评估方法','我是初学者，想先读容易理解的论文']){const b=node('button','ghost',text);b.type='button';b.onclick=()=>{input.value=text;input.focus()};suggestions.append(b)}wrap.append(suggestions);box.append(wrap)}
    function render(chat){current=chat;const fingerprint=JSON.stringify(chat.messages);if(fingerprint!==renderedMessages){renderedMessages=fingerprint;const box=$('#chatMessages'),nearBottom=box.scrollHeight-box.scrollTop-box.clientHeight<100;box.replaceChildren();if(!chat.messages.length)welcome();for(const m of chat.messages){const item=node('div','chat-message '+m.role);item.append(node('div','chat-role',m.role==='user'?'你':'研究助手'));const bubble=node('div','chat-bubble');if(m.role==='assistant'&&m.html)bubble.innerHTML=m.html;else bubble.textContent=m.text;item.append(bubble);box.append(item)}if(nearBottom||chat.messages.at(-1)?.role==='user')box.scrollTop=box.scrollHeight}$('#chatError').textContent=chat.error||'';const results=$('#chatResults');results.replaceChildren();for(const r of chat.recommendations){const a=node('a','','查看推荐 · '+new Date(r.at).toLocaleDateString());a.href=prefix+'/digests/'+encodeURIComponent(r.jobId);results.append(a)}controls();history()}
    async function poll(id){clearTimeout(timer);try{const chat=await api('/api/chats/'+encodeURIComponent(id));if(current?.id!==id)return;render(chat);if(chat.status==='running')timer=setTimeout(()=>poll(id),2500);else refreshHistory().catch(()=>{})}catch(error){if(current?.id!==id)return;$('#chatError').textContent=error.message+' 正在重试…';timer=setTimeout(()=>poll(id),5000)}}
    async function openChat(id){clearTimeout(timer);section.hidden=false;current={id,status:'loading',messages:[],recommendations:[]};renderedMessages='';busy=true;controls();try{render(await api('/api/chats/'+encodeURIComponent(id)));window.history.replaceState({},'',prefix+'/chats/'+encodeURIComponent(id));if(current.status==='running')timer=setTimeout(()=>poll(id),2500)}catch(error){$('#chatError').textContent=error.message}finally{busy=false;controls()}}
    async function newChat(){clearTimeout(timer);busy=true;controls();try{const chat=await post('/api/chats',{});renderedMessages='';render(chat);input.value='';sendAttempt=null;recommendAttempt=null;window.history.replaceState({},'',prefix+'/chats/'+chat.id);await refreshHistory();input.focus();return chat}catch(error){$('#chatError').textContent=error.message;throw error}finally{busy=false;controls()}}
    async function show(){section.hidden=false;section.scrollIntoView({behavior:'smooth',block:'start'});if(current){controls();return}welcome();busy=true;controls();try{await refreshHistory();if(chatList.length)await openChat(chatList[0].id)}catch(error){$('#chatError').textContent=error.message}finally{busy=false;controls()}}
    $('#chatOpen').onclick=show;$('#chatHide').onclick=()=>{section.hidden=true};$('#chatNew').onclick=()=>newChat().catch(()=>{});
    $('#chatForm').addEventListener('submit',async event=>{event.preventDefault();const text=input.value.trim();if(!text||busy||current?.status==='running')return;busy=true;controls();$('#chatError').textContent='';try{if(!current)await newChat();busy=true;controls();if(!sendAttempt||sendAttempt.chatId!==current.id||sendAttempt.text!==text)sendAttempt={chatId:current.id,text,requestId:newId()};const chat=await post('/api/chats/'+current.id+'/messages',sendAttempt);render(chat);input.value='';sendAttempt=null;recommendAttempt=null;timer=setTimeout(()=>poll(chat.id),1000);refreshHistory().catch(()=>{})}catch(error){$('#chatError').textContent=error.message}finally{busy=false;controls()}});
    input.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();$('#chatForm').requestSubmit()}});
    $('#chatRecommend').onclick=async()=>{if(!current||busy)return;busy=true;controls();try{const revision=current.id+':'+current.messages.at(-1)?.id;if(recommendAttempt?.revision!==revision)recommendAttempt={revision,requestId:newId()};const result=await post('/api/chats/'+current.id+'/recommendations',{requestId:recommendAttempt.requestId});location.href=result.digestUrl}catch(error){$('#chatError').textContent=error.message;busy=false;controls()}};
    if(initial?.type==='chat'){section.hidden=false;openChat(initial.id);refreshHistory().catch(()=>{})}else welcome();
  })();
  </script>`;
}
